In [1]:
import pandas as pd

file_path = "Dataset/Raw/Crimes_2001_to_Present.csv" 

df = pd.read_csv(file_path)

df.info()

C:\Users\hemin\AppData\Local\Temp\ipykernel_46828\3945311690.py:5: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8476328 entries, 0 to 8476327
Data columns (total 22 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Case Number           object
 2   Date                  object
 3   Block                 object
 4   IUCR                  object
 5   Primary Type          object
 6   Description           object
 7   Location Description  object
 8   Arrest                bool
 9   Domestic              bool
 10  Beat                  int64
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64
 18  Updated On            object
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 1.3+ GB

In [2]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13311263,JG503434,07/29/2022 03:39:00 AM,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,...,25.0,30.0,17,NaN,NaN,2022,04/18/2024 03:40:59 PM,NaN,NaN,NaN
1,13053066,JG103252,01/03/2023 04:44:00 PM,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,...,28.0,26.0,18,NaN,NaN,2023,01/20/2024 03:41:12 PM,NaN,NaN,NaN
2,12131221,JD327000,08/10/2020 09:45:00 AM,015XX N DAMEN AVE,0326,ROBBERY,AGGRAVATED VEHICULAR HIJACKING,STREET,True,False,...,1.0,24.0,03,1162795.0,1909900.0,2020,05/17/2025 03:40:52 PM,41.908418,-87.677407,"(41.908417822, -87.67740693)"
3,11227634,JB147599,08/26/2017 10:00:00 AM,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,...,42.0,32.0,02,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
4,13203321,JG415333,09/06/2023 05:00:00 PM,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,...,42.0,32.0,14,1174694.0,1901831.0,2023,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)"

In [3]:
summary = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str),
    "missing_values": df.isna().sum().values
})

summary

                                    column    dtype  missing_values
ID                                      ID    int64               0
Case Number                    Case Number   object               0
Date                                  Date   object               0
Block                                Block   object               0
IUCR                                  IUCR   object               0
Primary Type                  Primary Type   object               0
Description                    Description   object               0
Location Description  Location Description   object           15394
Arrest                              Arrest     bool               0
Domestic                          Domestic     bool               0
Beat                                  Beat    int64               0
District                          District  float64              47
Ward                                  Ward  float64          614819
Community Area              Community Area  float64          613686
FBI Code                          FBI Code   object               0
X Coordinate                  X Coordinate  float64           94397
Y Coordinate                  Y Coordinate  float64           94397
Year                                  Year    int64               0
Updated On                      Updated On   object               0
Latitude                          Latitude  float64           94397
Longitude                        Longitude  float64           94397
Location                          Location   object           94397

In [4]:
import pandas as pd

# df already loaded
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

use_cols = ["Date", "Primary Type", "Latitude", "Longitude", "Year"]
df = df[use_cols].copy()

# Drop rows with missing essential fields
df = df.dropna(subset=["Date", "Latitude", "Longitude"])

# Basic sanity
print(df.shape)
print(df["Year"].min(), df["Year"].max())
df.head()

(8381931, 5)
2001 2026

                 Date     Primary Type   Latitude  Longitude  Year
2 2020-08-10 09:45:00          ROBBERY  41.908418 -87.677407  2020
4 2023-09-06 17:00:00  CRIMINAL DAMAGE  41.886018 -87.633938  2023
5 2023-09-06 11:00:00            THEFT  41.871835 -87.626151  2023
6 2019-05-21 08:20:00         BURGLARY  41.856547 -87.695605  2019
7 2021-07-07 10:30:00      SEX OFFENSE  41.655116 -87.594883  2021

In [5]:
df.to_csv("Dataset/Processed/cleaned_crime.csv", index=False)